### ISSUE TITLE
Naming the module

### ISSUE THREAD

**Issue by ThomasPe** [json-schema-form/json-schema-builder#4]
Currently the app refers to the module just as "builder".
Angular Schema Forms are called "schemaForm" and have a sf-abbreviation, so my the Builder would perhaps be "schemaFormBuilder" with an sfb-abbreviation?

**Comment by nicklasb** [comment]
When you say sfb, I suppose you talk about the attributes of the directive?

``` html
<schemaFormBuilder sfb-model="model"></schemaFormBuilder>
```

**Comment by ThomasPe** [comment]
yeah

**Comment by nicklasb** [comment]
IMO, that sounds legit. 
(an example is never wrong, you know)

**Comment by ThomasPe** [comment]
sry bout that. its basically just what I've already posted here: https://github.com/json-schema-form/json-schema-builder/issues/3

Just making sure I'm not screwing up the naming conventions.

**Comment by nicklasb** [comment]
Oh, I meant nothing by that, just a hint.
Sorry, I realised I may have sounded a bit harsh. 

It is good that you asked. Worst thing when people don't interact.

**Comment by ThomasPe** [comment]
gotcha, no worries
